### ISSUE TITLE
TooLongFrameException

### ISSUE THREAD

**Issue by outrunthewolf** [openzipkin/docker-zipkin#106]
I'm a bit stuck with how to deal with this and was hoping someone could point me in the right direction.

This stack trace is from running any version of the docker image locally and trying to connect to the web interface.

```
org.jboss.netty.handler.codec.frame.TooLongFrameException: Maximum frame size of 67108864 exceeded
7/18/2016 11:02:48 PM	at com.facebook.nifty.codec.DefaultThriftFrameDecoder.tryDecodeFramedMessage(DefaultThriftFrameDecoder.java:102) [nifty-core-0.19.0.jar:nifty-parent-0.19.0]
7/18/2016 11:02:48 PM	at com.facebook.nifty.codec.DefaultThriftFrameDecoder.decode(DefaultThriftFrameDecoder.java:68) [nifty-core-0.19.0.jar:nifty-parent-0.19.0]
7/18/2016 11:02:48 PM	at com.facebook.nifty.codec.DefaultThriftFrameDecoder.decode(DefaultThriftFrameDecoder.java:33) [nifty-core-0.19.0.jar:nifty-parent-0.19.0]
7/18/2016 11:02:48 PM	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at com.facebook.nifty.codec.DefaultThriftFrameCodec.handleUpstream(DefaultThriftFrameCodec.java:42) [nifty-core-0.19.0.jar:nifty-parent-0.19.0]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at com.facebook.nifty.core.ChannelStatistics.handleUpstream(ChannelStatistics.java:79) [nifty-core-0.19.0.jar:nifty-parent-0.19.0]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.5.Final.jar:na]
7/18/2016 11:02:48 PM	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
7/18/2016 11:02:48 PM	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
7/18/2016 11:02:48 PM	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```

**Comment by adriancole** [comment]
this is usually the case when someone is accidentally using port 9410 for
http as opposed to 9411.

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin/pull/1540 will disable scribe by default
