### ISSUE TITLE
Java Heap Space OOM

### ISSUE THREAD

**Issue by teamenergy** [openzipkin/docker-zipkin#120]
Hi, 
We are running zipkin:latest on docker 1.2.1 in swarm mode. The server zipkin is running on has more than sufficient memory.
Periodically, zipkin will report a channel shutdown connection error, throw a Java Heap OOM, then tie up all the available cpu on the node. There is no recovery other than stopping the service and restarting it. There are no logs before the initial OOM. 
Any thoughts?

typical log output:
### 2016-09-28 09:16:33.673  INFO [zipkin-server,,,] 1 --- [           main] c.t.c.m.ZipkinServerApplication          : Started ZipkinServerApplication in 11.568 seconds (JVM running for 12.116)
2016-09-28 13:44:04.908 ERROR [zipkin-server,,,] 1 --- [.168.99.18:5672] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: connection error
2016-09-28 13:45:10.150  WARN [zipkin-server,,,] 1 --- [ask-scheduler-8] o.s.i.c.MessagePublishingErrorHandler    : Error message was not delivered.

java.lang.OutOfMemoryError: Java heap space
        at org.springframework.integration.channel.MessagePublishingErrorHandler.handleError(MessagePublishingErrorHandler.java:85) ~[spring-integration-core-4.2.5.RELEASE.jar!/:na]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:60) [spring-context-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_92]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_92]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

2016-09-28 13:45:10.152 ERROR [zipkin-server,,,] 1 --- [-ClientPoller-0] org.apache.tomcat.util.net.NioEndpoint   : 

java.lang.OutOfMemoryError: Java heap space

2016-09-28 13:45:10.152 ERROR [zipkin-server,,,] 1 --- [-ClientPoller-1] org.apache.tomcat.util.net.NioEndpoint   : 

java.lang.OutOfMemoryError: Java heap space

2016-09-28 13:45:10.152 ERROR [zipkin-server,,,] 1 --- [ndardContext[]]] org.apache.catalina.core.ContainerBase   : Unexpected death of background thread ContainerBackgroundProcessor[StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]

java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.ConcurrentHashMap$ValuesView.iterator(ConcurrentHashMap.java:4683) ~[na:1.8.0_92]
        at java.util.AbstractCollection.addAll(AbstractCollection.java:343) ~[na:1.8.0_92]
        at java.util.TreeSet.addAll(TreeSet.java:312) ~[na:1.8.0_92]
        at org.apache.catalina.webresources.Cache.backgroundProcess(Cache.java:190) ~[tomcat-embed-core-8.0.33.jar!/:8.0.33]
        at org.apache.catalina.webresources.StandardRoot.backgroundProcess(StandardRoot.java:595) ~[tomcat-embed-core-8.0.33.jar!/:8.0.33]
        at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5627) ~[tomcat-embed-core-8.0.33.jar!/:8.0.33]
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1377) ~[tomcat-embed-core-8.0.33.jar!/:8.0.33]
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1349) ~[tomcat-embed-core-8.0.33.jar!/:8.0.33]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

Exception in thread "ContainerBackgroundProcessor[StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]" java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.ConcurrentHashMap$ValuesView.iterator(ConcurrentHashMap.java:4683)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
2016-09-28 13:45:47.125  WARN [zipkin-server,,,] 1 --- [sleuth.sleuth-1] o.s.a.r.l.SimpleMessageListenerContainer : Consumer raised exception, processing can restart if the connection factory supports it

com.rabbitmq.client.ShutdownSignalException: connection error
        at com.rabbitmq.client.impl.AMQConnection.startShutdown(AMQConnection.java:723) ~[amqp-client-3.5.7.jar!/:na]
        at com.rabbitmq.client.impl.AMQConnection.shutdown(AMQConnection.java:713) ~[amqp-client-3.5.7.jar!/:na]
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:571) ~[amqp-client-3.5.7.jar!/:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_92]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_92]
        at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_92]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_92]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_92]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[na:1.8.0_92]
        at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288) ~[na:1.8.0_92]
        at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:95) ~[amqp-client-3.5.7.jar!/:na]
        at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:139) ~[amqp-client-3.5.7.jar!/:na]
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:536) ~[amqp-client-3.5.7.jar!/:na]
        ... 1 common frames omitted

        at java.util.TreeSet.addAll(TreeSet.java:312)
2016-09-28 13:46:04.911 ERROR [zipkin-server,,,] 1 --- [-ClientPoller-0] org.apache.tomcat.util.net.NioEndpoint   : 

java.lang.OutOfMemoryError: Java heap space

        at org.apache.catalina.webresources.Cache.backgroundProcess(Cache.java:190)
        at org.apache.catalina.webresources.StandardRoot.backgroundProcess(StandardRoot.java:595)
2016-09-28 13:49:05.183  INFO [zipkin-server,,,] 1 --- [sleuth.sleuth-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer: tags=[{amq.ctag-QKEr3Ah-JjhllOcXGVn8mg=sleuth.sleuth}], channel=Cached Rabbit Channel: AMQChannel(amqp://guest@192.168.99.18:5672/,1), conn: Proxy@559dc2c1 Shared Rabbit Connection: SimpleConnection@54191b31 [delegate=amqp://guest@192.168.99.18:5672/], acknowledgeMode=AUTO local queue size=0
        at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5627)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1377)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1349)
        at java.lang.Thread.run(Thread.java:745)

**Comment by adriancole** [comment]
This issue was moved to spring-cloud/spring-cloud-sleuth#415

**Comment by adriancole** [comment]
moved the issue as it doesn't appear this is using images defined in this repository. Ex openzipkin/zipkin doesn't have rabbit or sleuth built in. If I've mistaken, let me know.

**Comment by teamenergy** [comment]
I bow to your wisdom. I am trying to run a system with containers I’ve no control over and a Dev team that told me ‘go google it’ when I asked about zipkin ☹

If you think it apllies elsewhere, feel free
