### ISSUE TITLE
Zipkin+kafka+cassandra problem

### ISSUE THREAD

**Issue by hkroger** [openzipkin/docker-zipkin#122]
When I run zipkin with commend `docker-compose -f $DOCKER_ZIPKIN_DIR/docker-compose.yml -f $DOCKER_ZIPKIN_DIR/docker-compose-kafka.yml -f $DOCKER_ZIPKIN_DIR/docker-compose-cassandra.yml up`, I get this error:

```
kafka-zookeeper    | [2016-10-17 12:28:44,901] WARN [Controller-0-to-broker-0-send-thread], Controller 0's connection to broker Node(0, 192.168.99.100, 9092) was unsuccessful (kafka.controller.RequestSendThread)
kafka-zookeeper    | java.net.SocketTimeoutException: Failed to connect within 30000 ms
kafka-zookeeper    | 	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:228)
kafka-zookeeper    | 	at kafka.controller.RequestSendThread.liftedTree1$1(ControllerChannelManager.scala:172)
kafka-zookeeper    | 	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:171)
kafka-zookeeper    | 	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
```

Also earlier in the console output I see something like this:

```
kafka-zookeeper    | /kafka/bin/kafka-run-class.sh: line 34: shopt: not found
kafka-zookeeper    | /kafka/bin/kafka-run-class.sh: line 78: shopt: not found
```
I am assuming that the setup doesn't work, right?

If I install bash in kafka-zookeeper:

```
> docker exec -it kafka-zookeeper /bin/sh
```

And inside the docker:
```
> apk  add bash
```

I don't get the shopt error but I still get the connection error.

What to do?

**Comment by hkroger** [comment]
Apparently kafka is being hardcoded to ip `192.168.99.100`

```
/ # cat /kafka/config/*|grep 192
advertised.host.name=192.168.99.100
```

But Mac Native Docker gives it an IP `172.18.0.3`. At least in this case.

**Comment by hkroger** [comment]
Ah, I didn't see that I need to manually update `KAFKA_ADVERTISED_HOST` in `docker-compose-kafka.yml` ...
